name: housing
channels:
- conda-forge
- defaults
dependencies:
- python=3.9
- pandas=2.1.1
- scikit-learn=1.3.1
- annotated-types=0.7.0
- anyio=4.4.0
- bzip2=1.0.8
- ca-certificates=2024.7.4
- certifi=2024.7.4
- click=8.1.7
- dnspython=2.6.1
- email-validator=2.2.0
- email_validator-2.2.0
- exceptiongroup=1.2.2
- fastapi=0.112.0
- fastapi-cli=0.0.5
- h11=0.14.0
- h2=4.1.0
- hpack=4.0.0
- httpcore=1.0.5
- httpx=0.27.0
- hyperframe=6.0.1
- idna=3.7
- jinja2=3.1.4
- joblib=1.4.2
- libblas=3.9.0
- libcblas=3.9.0
- libcxx=18.1.8
- libffi=3.4.2
- libgfortran=5.0.0
- libgfortran5=13.2.0
- liblapack=3.9.0
- libopenblas=0.3.27
- libsqlite=3.46.0
- libzlib=1.3.1
- llvm-openmp=18.1.8
- markdown-it-py=3.0.0
- markupsafe=2.1.5
- mdurl=0.1.2
- ncurses=6.5
- numpy=1.26.4
- openssl=3.3.1
- pip=24.2
- pydantic=2.0.3
- pydantic-core=2.3.0
- pygments=2.18.0
- python-dateutil=2.9.0
- python-multipart=0.0.9
- python-tzdata=2024.1
- python_abi=3.9
- pytz=2024.1
- readline=8.2
- rich=13.7.1
- scipy=1.13.1
- setuptools=72.1.0
- shellingham=1.5.4
- six=1.16.0
- sniffio=1.3.1
- starlette=0.37.2
- threadpoolctl=3.5.0
- tk=8.6.13
- typer=0.12.3
- typer-slim=0.12.3
- typer-slim-standard=0.12.3
- typing-extensions=4.12.2
- typing_extensions=4.12.2
- tzdata=2024a
- uvicorn=0.30.4
- wheel=0.44.0
- xz=5.2.6
